#ifndef _TEXTPOSITIONS_
#define _TEXTPOSITIONS_

#define TEXT_START_X 1
#define TEXT_START_Y 15

#define TEXT_END_X 18
#define TEXT_END_Y 16

#define NAME_START_X 1
#define NAME_START_Y 1

#define INVENTORY_ITEM_START_X 5
#define INVENTORY_ITEM_START_Y 3

#define NAME_END_X 10

#define ICON_Y 1
#define HUMOR_ICON_X 15
#define RELATION_ICON_X 17

#endif //_TEXTPOSITIONS_